version: '3.7'
services:
  mongo1.dev:
    container_name: mongo1.dev
    image: mongo:6.0.2
    restart: always
    networks:
      - study
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 8180:8080
#    depends_on:
#      - zookeeper
#      - kafka
#    networks:
#      - study
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#
#  zookeeper:
#    container_name: zookeeper
#    image: confluentinc/cp-zookeeper:5.2.4
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 2181:2181
#    networks:
#      - study
#
#  kafka:
#    container_name: kafka
#    image: confluentinc/cp-kafka:5.3.1
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#      - 9997:9997
#    networks:
#      - study
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  study:
    external: true

volumes:
  mongodb_data: