version: '3.5'
services:
  mongodb:
    image: mongo:6.0.2
    restart: always
    #descomentar para ativar a autenticacao
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: