
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          replicationFactor: 1
      bindings:
        receiveOrderBuy-in-0:
          destination: order_buy
        receiveOrderSell-in-0:
          destination: order_sell
      function:
        definition: receiveOrderBuy;receiveOrderSell

