server:
  port: 8082

#Descomentar para o tipo de producer and consumer usando suppliers
#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          replicationFactor: 1
#        bindings:
#          orderBuy-out-0:
#            producer:
#              configuration:
#                key:
#                  serializer: org.apache.kafka.common.serialization.LongSerializer
#          orderSell-out-0:
#            producer:
#              configuration:
#                key:
#                  serializer: org.apache.kafka.common.serialization.LongSerializer
#      bindings:
#        orderBuy-out-0:
#          destination: orders-buy
#          content-type: application/json
#          producer:
#            configuration:
#              partitionCount: 1
#        orderSell-out-0:
#          destination: orders-sell
#          producer:
#            configuration:
#              partitionCount: 1
#      function:
#        definition: orderBuy



#producer usando streamBridge para destino dinamico
spring:
  cloud:
    stream:
      #primeiro nome do binding
      source: orderBuy
      kafka:
        binder:
          brokers: localhost:9092
          replicationFactor: 1
      bindings:
        orderBuy-out-0:
          destination: order-buy
          contentType: application/json
          producer:
            configuration:
              partitionCount: 1